{% set name = "moz-sql-parser" %}
{% set version = "3.18.19324" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: d04c09ff749b91819dac2ebaa68018b1ff56f8641211bcc8bc70d7134f1e049a

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv "

requirements:
  host:
    - pip
    - python
  run:
    - mo-future >=2.48.19205
    - pyparsing ==2.3.1
    - python

test:
  imports:
    - moz_sql_parser

about:
  home: "https://github.com/mozilla/moz-sql-parser"
  license: MPL-2.0
  license_family: "MOZILLA"
  license_file: "LICENSE"
  summary: "Extract Parse Tree from SQL"

extra:
  recipe-maintainers:
    - xhochy
