{% set name = "moz-sql-parser" %}
{% set version = "4.9.21002" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a2cb1d47c68cd84f4816f21e0e1802b546b39fe971684bb3100dd74944a4cb3c

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - python >=2.7
    - pip
  run:
    - python >=2.7
    - mo-dots 4.2.20340
    - mo-future 3.147.20327
    - mo-logs 4.3.20340

test:
  imports:
    - moz_sql_parser
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/klahnakoski/moz-sql-parser
  license: MPL-2.0
  license_family: MOZILLA
  license_file: LICENSE
  summary: Extract Parse Tree from SQL

extra:
  recipe-maintainers:
    - xhochy
