{% set name = "moz-sql-parser" %}
{% set version = "3.125.20293" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 609025695a5898faa50e1a679a25c0c07cd21a46002ba2b099c254c1a1f188dc

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - mo-future >=3.31.20024
    - pyparsing ==2.3.1
    - python >=2.7

test:
  imports:
    - moz_sql_parser
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/mozilla/moz-sql-parser
  license: MPL-2.0
  license_family: MOZILLA
  license_file: LICENSE
  summary: Extract Parse Tree from SQL

extra:
  recipe-maintainers:
    - xhochy
