travis:
  secure:
    BINSTAR_TOKEN: ipF7txkoJ5oYiKjIDSjfpahZyEqajyquQUUjQC9ZrOcGOobFKdkpGwNI7PIn0aW4v3uJNZI3J1vQ89H2bqJIII8WQq4ygDhJfIlbX9v/GIi+J4uFcLCVwIsMJ08siqSqzESSn3N4Az0U7q1L50I3pLDMw1UyJgQUDnIm154rX0oJcTrhNJ/jP/8GlbktHsgUsdTYwnG59yZzzBFDHRDw++n8OF7BcJMqGb1BIU78hNw2pJ8aYDv+D8lr15w1LPDyZnD7bv3A8wc2M3z7yHI1sIDS/Nu+PMfHuw+wf6OJYxy3jEpXHvl4PXamfqM/5fPC+IpdcxlFeBVR8Ch58wPVqjD2Gbd2+cmPzuva+GLdxlEyYXjXr88e4666oVuM2snQatqS58qSZMnIQlyMC/BNCIHoXBYBuWVXwJisxh3R6vMDsk7U6jAsfYcHFHbtObOQjVP7Mb9g/2eV7l6T3lQmQEgxUpH1SiR+xtT4ESQpPUgMKebA3OOReXe74bLYBIVg2WktetdeooTaTgwK2nEuREHyqyjKOALcnnXeVvvYCALniAJxddNCbO7sTU3lckNQgWGjAXlsEb+maUlBsBhe6no9PzYsWa1b9klcj+iBKNLJCvbNQx/OnrM8qiEpW2v01Mwu+ojh242JZB7+4fzY3mCxonki+0SOeXc66xTsGKs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
